In [3]:
import numpy as np
import pandas as pd

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [6]:
df = pd.read_csv('/content/drive/MyDrive/nmims/sem1/aiml/kshamta mam/14 09 24/customer.csv')

In [7]:
df.sample(5)
#purchased is dependent var
#lets do ordinal encoding on

age  gender review education purchased
47   38  Female   Good        PG       Yes
40   39    Male   Good    School        No
2    70  Female   Good        PG        No
46   64  Female   Poor        PG        No
39   76    Male   Poor        PG        No

In [8]:
df = df.iloc[:,2:] # for gender column we need a one hot coading hence not using

In [9]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [11]:
from sklearn.preprocessing import OrdinalEncoder

In [12]:
X_train

review education
31     Poor    School
3      Good        PG
7      Poor    School
11     Good        UG
28     Poor    School
12     Poor    School
35     Poor    School
36     Good        UG
4   Average        UG
27     Poor        PG
32  Average        UG
38     Good    School
33     Good        PG
19     Poor        PG
18     Good    School
29  Average        UG
5   Average    School
20  Average    School
1      Poor        UG
37  Average        PG
44  Average        UG
6      Good    School
42     Good        PG
9      Good        UG
8   Average        UG
23     Good    School
17     Poor        UG
24  Average        PG
2      Good        PG
45     Poor        PG
15     Poor        UG
25     Good    School
43     Poor        PG
49     Good        UG
22     Poor        PG
48     Good        UG
26     Poor        PG
16     Poor        UG
14     Poor        PG
40     Good    School

In [13]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])  # ,maintains the sequence good has high value or it will have the random no and its not good

In [14]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [15]:
X_train = oe.transform(X_train)

In [16]:
X_train

array([[0., 0.],
       [2., 2.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 2.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [2., 0.]])

In [17]:
oe.categories_  # only to see

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [18]:
X_train

array([[0., 0.],
       [2., 2.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 2.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [2., 0.]])

In [19]:
from sklearn.preprocessing import LabelEncoder  # read the sklearn label encoder #used when dependent variable has categorical data
#always used for dependent var only

In [20]:
le = LabelEncoder()

In [22]:
le.fit(Y_train)

LabelEncoder()

In [23]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [24]:
Y_train = le.transform(Y_train)
Y_test = le.transform(Y_test)

In [25]:
Y_train

array([1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0])